### PR TITLE
Added Internet Explorer for desktop and windows phone

### PR DESCRIPTION
**Pull request by magsout**

### CODE REVIEW

**Comment by miketaylr** [comment]
Ooh, thanks. I need to update the rest of the versions too--good reminder.

**Comment by magsout** [comment]
update useragent or add new useragent with new version of browser ?

**Comment by miketaylr** [comment]
Hmm, good question. Personally I would probably prefer just updating for some of them (like Desktop browsers except for IE), but it would be useful to have multiple versions for others things (Firefox OS, IE, ...other things). What do you think?

**Comment by magsout** [comment]
> but it would be useful to have multiple versions for others things (Firefox OS, IE, ...other things). What do you think?

Agreed.

**Pull request merged**
